stages:
    - build
    - deploy

#build:
#    image: gradle:6.7.1-jdk11
#    stage: build
#    script: ./gradlew clean build
#    before_script:
#        - export GRADLE_USER_HOME=`pwd`/.gradle
#    artifacts:
#        paths:
#            - ./build/libs/VetApp-0.0.1-SNAPSHOT.jar

deploy:
    image: docker:stable
    stage: deploy
#    variables:
#        CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
#        DOCKER_HOST: tcp://docker:2375
#        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    before_script:
        - echo 'pierwszy'
        - echo $test
        - echo $CI_PROJECT_PATH
        - echo $HEROKU_USER
        - echo $HEROKU_API_KEY
        - docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
#        - apk add --update curl && rm -rf /var/cache/apk/*
    script:
        - docker build\\
            --JAR_FILE="./build/libs/VetApp-0.0.1-SNAPSHOT.jar" \\
            --DB_URI=${HEROKU_DB_URI}\\
            --DB_USER=${HEROKU_DB_USER}\\
            --DB_PASSWORD=&{HEROKU_DB_PASSWORD}\\
            --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
        - docker push regisry.heroku.com/${HEROKU_APP_NAME}/web
