stages:
    - build
    - deploy

build:
    image: gradle:6.7.1-jdk11
    stage: build
    script: ./gradlew clean build
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
    artifacts:
        paths:
            - ./build/libs/VetApp-0.0.1-SNAPSHOT.jar

deploy:
    image: docker:stable
    stage: deploy
    variables:
        CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
        DOCKER_HOST: tcp://docker:2375
        DOCKER_DRIVER: overlay2
        IMAGE_ID: $(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})
    services:
        - docker:dind
    before_script:
        - docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
        - apk add --update curl && rm -rf /var/cache/apk/*
    script:
        - docker build --build-arg JAR_FILE="./build/libs/VetApp-0.0.1-SNAPSHOT.jar" --build-arg DB_URI=$HEROKU_DB_URI --build-arg DB_USER=$HEROKU_DB_USER --build-arg DB_PASSWORD=$HEROKU_DB_PASSWORD --tag registry.heroku.com/$HEROKU_APP_NAME/web .
        - docker push registry.heroku.com/$HEROKU_APP_NAME/web
        - curl \
            -n \
            -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -d '{"update"&#58; [{"type":"web", "docker_image":"'"$IMAGE_ID"'"}]}' \
            -H "Content-Type&#58; application/json" \
            -H "Accept&#58; application/vnd.heroku+json; version=3" \
            -H "Authorization&#58; Bearer $HEROKU_API_KEY"
