stages:
    - build

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    image: gradle:6.8.3-jdk11
    stage: build
    script: ./gradlew clean build
    artifacts:
        paths:
            - ./build/libs/VetApp-0.0.1-SNAPSHOT.jar
