version: "3"
services:
  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_PASSWORD: kokiko
    ports:
      - 5432:5432
  vetapp:
    image: vetapp
    container_name: vetapp
    build:
      args:
        DB_URI: "jdbc:postgresql://database:5432/postgres"
        DB_USER: "postgres"
        DB_PASSWORD: "kokiko"
        PORT: 8080
      context: .
    ports:
      - 8080:8080
    depends_on:
      - database
